# Generated by Django 4.0.3 on 2022-05-10 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('create_date', models.DateField(default=datetime.date(2022, 5, 10))),
                ('direction', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
