# Generated by Django 4.0.4 on 2022-05-17 06:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_district_region_alter_group_create_date_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='create_date',
            field=models.DateField(default=datetime.date(2022, 5, 17)),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.district')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.group')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.region')),
            ],
        ),
    ]
